name: Auto Update Device List

on:
  schedule:
    - cron: "*/10 * * * *" # প্রতি 10 মিনিটে রান হবে
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # GitHub repo write permission

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Run PHP Script
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Execute Script
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: php php.php

    - name: Commit & Push changes
      run: |
        git config user.name "AutoBot"
        git config user.email "bot@github.com"
        git add users.json
        git commit -m "Auto update device list" || echo "No changes to commit"
        git push
